package com.forkexec.pts.ws.cli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.Map;

import javax.xml.ws.BindingProvider;

import com.forkexec.pts.ws.BadInitFault_Exception;
import com.forkexec.pts.ws.EmailAlreadyExistsFault_Exception;
import com.forkexec.pts.ws.InvalidEmailFault_Exception;
import com.forkexec.pts.ws.InvalidPointsFault_Exception;
import com.forkexec.pts.ws.NotEnoughBalanceFault_Exception;
import com.forkexec.pts.ws.PointsPortType;
import com.forkexec.pts.ws.PointsService;


import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;

import com.forkexec.pts.ws.*;

import javax.xml.ws.Response;
import java.util.concurrent.ExecutionException;

import javax.xml.ws.AsyncHandler;
import java.util.concurrent.Future;

/**
 * Client port wrapper.
 *
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class PointsClient{

	/** WS service */
	PointsService service = null;

	/** WS port (port type is the interface, port is the implementation) */
	PointsPortType port = null;

	/** UDDI server URL */
	private String uddiURL = null;

	/** WS name */
	private String wsName = null;

	/** WS end point address */
	private String wsURL = null; // default value is defined inside WSDL

	public String getWsURL() {
		return wsURL;
	}

	/** output option **/
	private boolean verbose = false;

	public boolean isVerbose() {
		return verbose;
	}

	public void setVerbose(boolean verbose) {
		this.verbose = verbose;
	}

	/** constructor with provided web service URL */
	public PointsClient(String wsURL) throws PointsClientException {
		this.wsURL = wsURL;
		createStub();
	}

	/** constructor with provided UDDI location and name */
	public PointsClient(String uddiURL, String wsName) throws PointsClientException {
		this.uddiURL = uddiURL;
		this.wsName = wsName;
		uddiLookup();
		createStub();
	}

	/** UDDI lookup */
	private void uddiLookup() throws PointsClientException {
		try {
			if (verbose)
				System.out.printf("Contacting UDDI at %s%n", uddiURL);
			UDDINaming uddiNaming = new UDDINaming(uddiURL);

			if (verbose)
				System.out.printf("Looking for '%s'%n", wsName);
			wsURL = uddiNaming.lookup(wsName);

		} catch (Exception e) {
			String msg = String.format("Client failed lookup on UDDI at %s!", uddiURL);
			throw new PointsClientException(msg, e);
		}

		if (wsURL == null) {
			String msg = String.format("Service with name %s not found on UDDI at %s", wsName, uddiURL);
			throw new PointsClientException(msg);
		}
	}

	/** Stub creation and configuration */
	private void createStub() {
		if (verbose)
			System.out.println("Creating stub ...");
		service = new PointsService();
		port = service.getPointsPort();

		if (wsURL != null) {
			if (verbose)
				System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}

	// remote invocation methods ----------------------------------------------

	
	public void activateUser(String userEmail) throws EmailAlreadyExistsFault_Exception, InvalidEmailFault_Exception {
		port.activateUser(userEmail);
	}

	
	public PointsView getPoints(String userEmail) throws InvalidEmailFault_Exception {
		return port.getPoints(userEmail);
	}

	
	public int setPoints(String userEmail, int pointsToAdd, int tag)
			throws InvalidEmailFault_Exception, InvalidPointsFault_Exception, NotEnoughBalanceFault_Exception {
		return port.setPoints(userEmail, pointsToAdd, tag);
	}

	

	// control operations -----------------------------------------------------

	
	public String ctrlPing(String inputMessage) {
		return port.ctrlPing(inputMessage);
	}

	
	public void ctrlClear() {
		port.ctrlClear();
	}

	
	public void ctrlInit(int startPoints) throws BadInitFault_Exception {
		port.ctrlInit(startPoints);
	}


	// response operations ------------------------------------------------------

	
	public Response<GetPointsResponse> getPointsAsync(String userEmail) {
        return port.getPointsAsync(userEmail);
    }

    
	public Future<?> getPointsAsync(String userEmail, AsyncHandler<GetPointsResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

	
	public Response<ActivateUserResponse> activateUserAsync(String userEmail) {
        return port.activateUserAsync(userEmail);
    }

    
	public Future<?> activateUserAsync(String userEmail, AsyncHandler<ActivateUserResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

   	
	public Response<SetPointsResponse> setPointsAsync(String userEmail, int pointsToAdd, int tag) {
        return port.setPointsAsync(userEmail, pointsToAdd, tag);
    }

    
	public Future<?> setPointsAsync(String userEmail, int pointsToAdd, int tag, AsyncHandler<SetPointsResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

   	
	public Response<CtrlPingResponse> ctrlPingAsync(String inputMessage) {
        return port.ctrlPingAsync(inputMessage);
    }

    
	public Future<?> ctrlPingAsync(String inputMessage, AsyncHandler<CtrlPingResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

   	
	public Response<CtrlClearResponse> ctrlClearAsync() {
        return port.ctrlClearAsync();
    }

    
	public Future<?> ctrlClearAsync(AsyncHandler<CtrlClearResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

   	
	public Response<CtrlInitResponse> ctrlInitAsync(int startPoints) {
        return port.ctrlInitAsync(startPoints);
    }

    
	public Future<?> ctrlInitAsync(int startPoints, AsyncHandler<CtrlInitResponse> asyncHandler) {
		// TODO Auto-generated method stub
		return null;
	}

}
